## What are Tensors?

Tensors are a fundamental data structure used in the field of machine learning and scientific computing.
At their core, tensors are multi-dimensional arrays

First, we'll import pytorch.

In [1]:
import torch

Let's see a few basic tensor manipulations. First, just a few of the ways to create tensors:

In [2]:
# Using a List

lst = list(range(10))
print(f"List :{lst}")

a = torch.tensor(lst)
print(f"Torch Tensor:{a}")

List :[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Torch Tensor:tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
# Creating a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])

# Creating a 3D tensor
tensor_3d = torch.tensor([[[1, 2, 3],
                           [4, 5, 6]],
                          [[7, 8, 9],
                           [10, 11, 12]]])

# Creating a 4D tensor
tensor_4d = torch.tensor([[[[1, 2],
                            [3, 4]],
                           [[5, 6],
                            [7, 8]]],
                          [[[9, 10],
                            [11, 12]],
                           [[13, 14],
                            [15, 16]]]])

# Print the tensors
print("2D Tensor (Matrix):")
print(tensor_2d)
print("Shape:", tensor_2d.shape)

print("\n3D Tensor:")
print(tensor_3d)
print("Shape:", tensor_3d.shape)

print("\n4D Tensor:")
print(tensor_4d)
print("Shape:", tensor_4d.shape)


2D Tensor (Matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

3D Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Shape: torch.Size([2, 2, 3])

4D Tensor:
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
Shape: torch.Size([2, 2, 2, 2])


In [4]:
tensor_2d.dtype

torch.int64

In [5]:
# Using a Numpy Array
import numpy as np

np_array = np.array(list(range(10)))
print(f"Numpy array:{np_array} || datatype : {type(np_array)}")

# Convert NumPy array to PyTorch tensor
torch_tensor = torch.tensor(np_array)
# or
torch_tensor = torch.from_numpy(np_array)
print(f"Torch Tensor:{torch_tensor} || datatype : {type(torch_tensor)}")

# Convert tensor to numpy array
c = torch_tensor.numpy()
print(f"Numpy array:{c} || datatype : {type(c)}")

Numpy array:[0 1 2 3 4 5 6 7 8 9] || datatype : <class 'numpy.ndarray'>
Torch Tensor:tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) || datatype : <class 'torch.Tensor'>
Numpy array:[0 1 2 3 4 5 6 7 8 9] || datatype : <class 'numpy.ndarray'>


In [6]:
hashmap = {1:1,2:2,3:3}
print("Datatype",type(hashmap))
print(torch.tensor(hashmap))

Datatype <class 'dict'>


RuntimeError: Could not infer dtype of dict

In [7]:
hashset = set([1,22,3,5,6,4,8])
print(type(hashset))
print(torch.tensor(hashset))

<class 'set'>


RuntimeError: Could not infer dtype of set

In [8]:
tup = tuple([("a",2),("b",4),("c",6)])
print(type(tup))
print(torch.tensor(tup))

<class 'tuple'>


ValueError: too many dimensions 'str'

In [9]:
tup_uniform = tuple([(1,2),(3,4),(5,6)])
print(type(tup_uniform))
print(torch.tensor(tup_uniform))

<class 'tuple'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [10]:
z = torch.zeros((5, 3))
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


Above, we create a 5x3 matrix filled with zeros,the zeros are 32-bit floating point numbers, which is the default PyTorch.

We can change the default datatype as well.

In [11]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


torch.rand() :Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1).

It's common to initialize learning weights randomly, often with a specific seed for reproducibility of results:

In [12]:
torch.manual_seed(1)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

torch.manual_seed(42)
r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed

A random tensor:
tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])

A different random tensor:
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

Should match r1:
tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])


In [13]:
# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [14]:
# Basic indexing: Access a single element
print("Basic indexing - Single element:", tensor[1, 2])

Basic indexing - Single element: tensor(6)


In [15]:
# Slicing: Access a sub-tensor
print("Slicing - Sub-tensor:")
print(tensor[1:, :])

Slicing - Sub-tensor:
tensor([[4, 5, 6],
        [7, 8, 9]])


In [16]:
# Fancy indexing: Access specific elements using a list of indices
indices = torch.tensor([0, 2])
print("Fancy indexing - Specific elements:")
print(tensor[:, indices])

Fancy indexing - Specific elements:
tensor([[1, 3],
        [4, 6],
        [7, 9]])


In [17]:
# Masked indexing: Access elements based on a boolean mask
mask = tensor > 5
print("Masked indexing - Elements satisfying condition:")
print(tensor[mask])

Masked indexing - Elements satisfying condition:
tensor([6, 7, 8, 9])


In [18]:
# reshape method
tensor1 = torch.tensor(list(range(36)))

In [19]:
tensor1.reshape(-1,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])

PyTorch tensors perform arithmetic operations intuitively. Tensors of similar shapes may be added, multiplied, etc. It also support Broadcasting similar to numpy arrays.

In [20]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2 # every element is multiplied by 2
print(twos)

threes = ones + twos       # additon allowed because shapes are similar
print(threes)              # tensors are added element-wise
print(threes.shape)        # this has the same dimensions as input tensors

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


In [21]:
# Supports Broadcasting

a1 = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(f"a1 shape :{a1.shape}")

b1 = torch.tensor([[10],
                  [20]])
print(f"b1 shape :{b1.shape}")

# Perform element-wise addition (broadcasting)
c1 = a1 + b1

print(c1)

a1 shape :torch.Size([2, 3])
b1 shape :torch.Size([2, 1])
tensor([[11, 12, 13],
        [24, 25, 26]])


In [22]:
# Due to inappropriate tensor shapes
r1 = torch.rand(3,3,1)
r2 = torch.rand(3,3,2)
r3 = r1 + r2
print(r3)

tensor([[[0.3344, 0.4928],
         [1.2548, 1.3723],
         [0.8951, 1.3342]],

        [[1.4100, 1.0682],
         [0.7675, 0.9857],
         [0.7231, 0.7786]],

        [[1.1626, 1.4367],
         [1.2964, 0.5359],
         [1.4926, 1.3223]]])


Here's a small sample of the mathematical operations available:

In [23]:
torch.manual_seed(2)
r = torch.rand(2, 2) - 0.5 * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

A random matrix, r:
tensor([[-0.3853, -0.6190],
        [-0.3629, -0.5255]])


In [24]:
# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))


Absolute value of r:
tensor([[0.3853, 0.6190],
        [0.3629, 0.5255]])


In [25]:
# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))


Inverse sine of r:
tensor([[-0.3955, -0.6675],
        [-0.3714, -0.5533]])


In [26]:
# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))


Determinant of r:
tensor(-0.0221)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.7523, -0.6588],
        [-0.6588,  0.7523]]),
S=tensor([0.9690, 0.0228]),
V=tensor([[ 0.5459, -0.8379],
        [ 0.8379,  0.5459]]))


In [27]:
# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))


Average and standard deviation of r:
(tensor(0.1210), tensor(-0.4732))

Maximum value of r:
tensor(-0.3629)
